apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: nginx
    newName: nginx
    newTag: "1.29.4" 
   
patches:
  - path: configmap-patch.yaml
  - path: patch-service.yaml
