apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-index
  
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Custom Page</title>
    </head>
    <body>
      <h1>Welcome to My Third Demo Kubernetes Site!</h1>
    </body>
    </html>